---
title: "Post-COMPASS Plots"
author: "Jolie Phan"
output: 
  html_document:
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: 4
date: "version `r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Load libraries

```{r, message=F}
library(here)
library(tidyverse)
library(COMPASS)
library(ggplot2)
library(data.table)
library(broom)
library(psych)
library(corrplot)
library(ggpubr)
library(knitr)
library(kableExtra)
library(cowplot)
library(purrr)
library(flowWorkspace)
library(GGally)
library(patchwork)
library(ComplexHeatmap)
library(ggbeeswarm)
library(ggh4x)
source(here::here("scripts/Helper_Functions.R"))
```

# Read in data

```{r read in data}
save_output <- TRUE

stims_for_compass_runs <- c("PP1", "TB WCL")
parent_nodes_for_compass_runs <- c("CD4+", "CD8+")
stims_for_compass_runs_rep <- rep(stims_for_compass_runs, each = length(parent_nodes_for_compass_runs))
parent_nodes_for_compass_runs_rep <- rep(parent_nodes_for_compass_runs, times = length(stims_for_compass_runs))
crList <- purrr::pmap(.l = list(parent_nodes_for_compass_runs_rep,
                                stims_for_compass_runs_rep),
                      .f = function(parent, currentStim) {
                        currentStimForFile <- gsub(" ", "_", currentStim)
                        crPath <- here::here(sprintf("out/CompassOutput/%s/%s/COMPASSResult_%s_%s.rds", parent, currentStimForFile, parent, currentStimForFile))
                        readRDS(crPath)
                      }) %>% 
  set_names(gsub("+", "", gsub(" ", "_", paste0(parent_nodes_for_compass_runs_rep, "_", stims_for_compass_runs_rep)), fixed=TRUE))
names(crList)
CD4RunNames <- c("CD4_PP1", "CD4_TB_WCL")
CD8RunNames <- c("CD8_PP1", "CD8_TB_WCL")

gsPath <- here::here("out/GatingSets/RSTR_Treg_GatingSet")
gs <- load_gs(gsPath)

if(!dir.exists(here::here("processed_data"))) {
    cat(sprintf("Creating folder %s\n", here::here("processed_data")))
    dir.create(here::here("processed_data"), recursive = T)
}

if(!dir.exists(here::here("out/post_compass_plots/magnitude_plots"))) {
    cat(sprintf("Creating folder %s\n", here::here("out/post_compass_plots/magnitude_plots")))
    dir.create(here::here("out/post_compass_plots/magnitude_plots"), recursive = T)
}

if(!dir.exists(here::here("out/post_compass_plots/fs_plots"))) {
    cat(sprintf("Creating folder %s\n", here::here("out/post_compass_plots/fs_plots")))
    dir.create(here::here("out/post_compass_plots/fs_plots"), recursive = T)
  }
```

```{r, eval=FALSE, include=FALSE}
# Playing around with shinyCOMPASS
library(shiny)
library(shinyGridster)
shinyCOMPASS(crList[["CD4_PP1"]], dir = here::here())
```

# Set font

```{r}
# Arial font setup. Downloaded afms from https://github.com/microsoft/microsoft-r-open/tree/ec3fd89e5fb5794bd8149905c134ad801bb61800
Arial <- Type1Font(family = "Arial",
                   metrics = c(here::here("data/Arial_afm/ArialMT.afm"),
                               here::here("data/Arial_afm/ArialMT-Bold.afm"),
                               here::here("data/Arial_afm/ArialMT-Italic.afm"),
                               here::here("data/Arial_afm/ArialMT-BoldItalic.afm")))
windowsFonts("Arial" = windowsFont("Arial"))
pdfFonts(Arial = Arial)

# Naive PRE is light blue, Naive POST is dark blue. "#54A8E1" "#196293"
# Conv PRE is light red, Conv POST is dark red "#EB4D4F" "#9D1213"
```

# Stacked heat maps by infection status

First, set cytokine order and colors for labels.

```{r}
cytokine_order_for_annotation <- c("CD154", "CD137", "CTLA4", "OX40")
cytokine_row_name_text <- c("CD154", "CD137", "CTLA-4", "OX40") # make sure this is in the same order as "cytokine_order_for_annotation"

status_colors <- c("Pneg" = "#984EA3", "TST+" = "#4DAF4A")
stim_colors <- c("PP1" = "#8dd3c7", "TB WCL" = "#ffffb3") 
row_ann_colors <- list(`Stim` = stim_colors, `Status` = status_colors)

mergeMatricesForPlotCOMPASSResultStack_tmp <- utils::getFromNamespace("mergeMatricesForPlotCOMPASSResultStack", "COMPASS")
```

## CD4+

```{r, fig.width=5, fig.height=7}
cd4_data2plot <- mergeMatricesForPlotCOMPASSResultStack_tmp(crList[CD4RunNames],
                                                            threshold=0.01,
                                                            minimum_dof=1,
                                                            maximum_dof=Inf,
                                                            row_annotation = c("Stim", "Status"),
                                                            variable = "Stim")
if(save_output) {
  saveRDS(cd4_data2plot, here::here("processed_data/Merged_Treg_CD4_COMPASS_Data.rds"))
}
cd4_merged_COMPASSResult <- crList$`CD4_PP1`
cd4_merged_COMPASSResult$fit$mean_gamma <- cd4_data2plot$MMerged
cd4_merged_COMPASSResult$fit$categories <- cd4_data2plot$catsMerged %>% mutate_all(~ as.numeric(as.character(.))) %>% mutate(Counts = rowSums(.))
rownames(cd4_merged_COMPASSResult$fit$categories) <- rownames(cd4_data2plot$catsMerged)
cd4_merged_COMPASSResult$data$meta <- cd4_data2plot$rowannMerged
cd4_merged_COMPASSResult$data$meta$Run_SAMPLE_ID <- rownames(cd4_merged_COMPASSResult$data$meta)
cd4_merged_COMPASSResult$data$meta$Stim <- factor(dplyr::recode(sub("^4_", "", cd4_merged_COMPASSResult$data$meta$Stim), "CD4_PP1" = "PP1", "CD4_TB_WCL" = "TB WCL"), levels = c("PP1","TB WCL"))
cd4_merged_COMPASSResult$data$individual_id <- "Run_SAMPLE_ID"

cd4_heatmap <- plot.COMPASSResult.ComplexHeatmap(cr = cd4_merged_COMPASSResult,
                                                 subset_keep = NULL,
                                  row_annotation = c("Stim", "Status"),
                                  cytokine_order_for_annotation = cytokine_order_for_annotation,
                                  cytokine_row_name_text = cytokine_row_name_text,
                                  dichotomize_by_cytokine = NULL,
                                  dichotomize_by_cytokine_color = "#999999",
                                  row_annotation_colors = row_ann_colors,
                                  staircase_cytokine_annotation = TRUE,
                                  row_gap = unit(0.03, "in"))

draw(cd4_heatmap, gap = unit(0.1, "in"), merge_legends = T, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")
```

## CD8+

```{r, fig.width=5, fig.height=7}
cd8_data2plot <- mergeMatricesForPlotCOMPASSResultStack_tmp(crList[CD8RunNames],
                                                            threshold=0.01,
                                                            minimum_dof=1,
                                                            maximum_dof=Inf,
                                                            row_annotation = c("Stim", "Status"),
                                                            variable = "Stim")
if(save_output) {
  saveRDS(cd8_data2plot, here::here("processed_data/Merged_Treg_CD8_COMPASS_Data.rds"))
}
cd8_merged_COMPASSResult <- crList$`CD8_PP1`
cd8_merged_COMPASSResult$fit$mean_gamma <- cd8_data2plot$MMerged
cd8_merged_COMPASSResult$fit$categories <- cd8_data2plot$catsMerged %>% mutate_all(~ as.numeric(as.character(.))) %>% mutate(Counts = rowSums(.))
rownames(cd8_merged_COMPASSResult$fit$categories) <- rownames(cd8_data2plot$catsMerged)
cd8_merged_COMPASSResult$data$meta <- cd8_data2plot$rowannMerged
cd8_merged_COMPASSResult$data$meta$Run_SAMPLE_ID <- rownames(cd8_merged_COMPASSResult$data$meta)
cd8_merged_COMPASSResult$data$meta$Stim <- factor(dplyr::recode(sub("^8_", "", cd4_merged_COMPASSResult$data$meta$Stim), "CD8_PP1" = "PP1", "CD8_TB_WCL" = "TB WCL"), levels = c("PP1","TB WCL"))
cd8_merged_COMPASSResult$data$individual_id <- "Run_SAMPLE_ID"

cd8_heatmap <- plot.COMPASSResult.ComplexHeatmap(cr = cd8_merged_COMPASSResult,
                                                 subset_keep = NULL,
                                  row_annotation = c("Stim", "Status"),
                                  cytokine_order_for_annotation = cytokine_order_for_annotation,
                                  cytokine_row_name_text = cytokine_row_name_text,
                                  dichotomize_by_cytokine = NULL,
                                  dichotomize_by_cytokine_color = "#999999",
                                  row_annotation_colors = row_ann_colors,
                                  staircase_cytokine_annotation = TRUE,
                                  row_gap = unit(0.03, "in"))

draw(cd8_heatmap, gap = unit(0.1, "in"), merge_legends = T, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")
```

# Boxplots by infection status

Note: all p-values are unadjusted.

```{r}
# Set cytokine order and colors for labels
cytokine_order_for_annotation = c("CD154", "CD137", "CTLA4", "OX40")
cytokine_row_name_text = c("CD154", "CD137", "CTLA-4", "OX40") # make sure this is in the same order as "cytokine_order_for_annotation"
fill_colors <- c("Pneg" = "#984EA3", "TST+" = "#4DAF4A")
```

## CD4

```{r}
treg_cd4_bg_corr_boxplots <- pmap(.l = list(CD4RunNames,
                                       c("CD4+", "CD4+"),
                                       list(c(-0.0015, 0.035), c(-0.0015, 0.085)),
                                       c(7, 7),
                                       c(1.3, 1.3),
                                       list(NULL, NULL),
                                       c("PP1", "TB WCL")),
                             .f = function(n, p, y, p_text_size, left_cats_heatmap_padding, dichotomize_by_cytokine, main_title) {
                               # "staircase effect" for categories df heatmap gets done automatically, unlike in heatmap
                               # Returned plot is gtable
                               make_boxplot_for_COMPASS_run(crList[[n]], run_name = n, parentSubset = p, add_legend = T, 
                                                            current_ylim = y, include_0_line=T, 
                                                            cytokine_order_for_annotation=cytokine_order_for_annotation,
                                                            cytokine_row_name_text = cytokine_row_name_text, 
                                                            p_text_size=p_text_size,
                                                            group_by_order=c("Pneg", "TST+"),
                                                            group_by_colors=fill_colors,
                                                            group_by_labels = c("Pneg", "TST+"),
                                                            group_by_colname="Status",
                                                            zeroed_BgCorr_stats = FALSE, zeroed_BgCorr_plot = FALSE,
                                                            dichotomize_by_cytokine = dichotomize_by_cytokine, dichotomize_by_cytokine_color="#999999",
                                                            cats_heatmap_left_padding=left_cats_heatmap_padding, main_title = main_title,
                                                            save_test_results=TRUE, output_folder=here::here("processed_data"), adj_pval = FALSE, dataset_name = "Treg")
                         })
names(treg_cd4_bg_corr_boxplots) <- CD4RunNames
if(save_output) {
  saveRDS(treg_cd4_bg_corr_boxplots, here::here("processed_data/Treg_CD4_make_boxplot_for_COMPASS_run_list.rds"))
}
```

```{r, fig.width=17, fig.height=7}
grid.draw(treg_cd4_bg_corr_boxplots[["CD4_PP1"]]$Plot)
```

```{r, fig.width=17, fig.height=7}
grid.draw(treg_cd4_bg_corr_boxplots[["CD4_TB_WCL"]]$Plot)
```

## CD8

```{r}
treg_cd8_bg_corr_boxplots <- pmap(.l = list(CD8RunNames,
                                       c("CD8+", "CD8+"),
                                       list(c(-0.0015, 0.007), c(-0.0015, 0.04)),
                                       c(7, 7),
                                       c(1.3, 1.3),
                                       list(NULL, NULL),
                                       c("PP1", "TB WCL")),
                             .f = function(n, p, y, p_text_size, left_cats_heatmap_padding, dichotomize_by_cytokine, main_title) {
                               # "staircase effect" for categories df heatmap gets done automatically, unlike in heatmap
                               # Returned plot is gtable
                               make_boxplot_for_COMPASS_run(crList[[n]], run_name = n, parentSubset = p, add_legend = T, 
                                                            current_ylim = y, include_0_line=T, 
                                                            cytokine_order_for_annotation=cytokine_order_for_annotation,
                                                            cytokine_row_name_text = cytokine_row_name_text, 
                                                            p_text_size=p_text_size,
                                                            group_by_order=c("Pneg", "TST+"),
                                                            group_by_colors=fill_colors,
                                                            group_by_labels = c("Pneg", "TST+"),
                                                            group_by_colname="Status",
                                                            zeroed_BgCorr_stats = FALSE, zeroed_BgCorr_plot = FALSE,
                                                            dichotomize_by_cytokine = dichotomize_by_cytokine, dichotomize_by_cytokine_color="#999999",
                                                            cats_heatmap_left_padding=left_cats_heatmap_padding, main_title = main_title,
                                                            save_test_results=TRUE, output_folder=here::here("processed_data"), adj_pval = FALSE, dataset_name = "Treg")
                         })
names(treg_cd8_bg_corr_boxplots) <- CD8RunNames
if(save_output) {
  saveRDS(treg_cd8_bg_corr_boxplots, here::here("processed_data/Treg_CD8_make_boxplot_for_COMPASS_run_list.rds"))
}
```

```{r, fig.width=17, fig.height=8}
grid.draw(treg_cd8_bg_corr_boxplots[["CD8_PP1"]]$Plot)
```

```{r, fig.width=12, fig.height=8}
grid.draw(treg_cd8_bg_corr_boxplots[["CD8_TB_WCL"]]$Plot)
```

# FS

```{r}
fs_pfs_df <- lapply(c(CD4RunNames, CD8RunNames), function(n) {
  as.data.frame(COMPASS::FunctionalityScore(crList[[n]])) %>%
    rownames_to_column("SAMPLE ID") %>% 
    rename(FS = `COMPASS::FunctionalityScore(crList[[n]])`) %>% 
    left_join(as.data.frame(COMPASS::PolyfunctionalityScore(crList[[n]])) %>%
      rownames_to_column("SAMPLE ID") %>% 
      rename(PFS = `COMPASS::PolyfunctionalityScore(crList[[n]])`),
      by = "SAMPLE ID") %>% 
    mutate(COMPASS_run = n)
  } ) %>% 
  data.table::rbindlist() %>% 
  separate(COMPASS_run, into = c("parent", "Stim"), remove = F, extra = "merge") %>% 
  left_join(crList$CD4_PP1$data$meta %>%
              dplyr::select(`SAMPLE ID`, Status))

fs_pfs_df$Status <- factor(fs_pfs_df$Status, levels = c("Pneg", "TST+"))
```

Write out the functionality scores to a file

```{r}
if(save_output) {
  fs_pfs_dat_2save <- fs_pfs_df %>% 
    # Convert the numeric columns to character type after rounding to 20 digits. This will help ensure consistency when writing and reading the data to a file
    mutate_at(vars("FS", "PFS"), ~ format(., digits = 20))
  
  write.csv(fs_pfs_dat_2save,
            here::here("processed_data/RSTR_Treg_FS_PFS.csv"), row.names = F)
}
```

Set colors 

```{r}
fill_colors <-  c("Pneg" = "#984EA3", "TST+" = "#4DAF4A")
```

Use Wilcoxon rank-sum test to compare across groups. 
Show the medians in each group.
Note: p-values are adjusted.

```{r, fig.width=4, fig.height=5}
fs_plots <- pmap(list(rep(c("PP1", "TB_WCL"), times = 2),
                      rep(c("CD4", "CD8"), each = 2)),
                 function(current_stim, cd4_or_cd8) {
                   split_fs_pfs_plot(df = fs_pfs_df, "FS", current_stim, cd4_or_cd8, fill_colors = fill_colors, 
                                     group_by_colname = "Status")
                   })
names(fs_plots) <- paste0(rep(c("CD4", "CD8"), each = 2), "_", rep(c("PP1", "TB_WCL"), times = 2))
fs_plots
```