---
title: "Treg Panel CD4 T cells Analysis"
author: "Jolie Phan"
output: 
  html_document:
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: 4
date: "version `r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---

Of CD4 T cells, analyze the expression of OX40, CTLA-4, CXCR3, CCR6, CD45RA, CCR7, RORyT, TBET, IFNg, and IL17a.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Load libraries

```{r}
library(tidyverse)
library(flowWorkspace)
library(here)
library(ggplot2)
library(ggbeeswarm)
library(ggh4x)
source(here::here("scripts/Helper_Functions.R")) # for make_mag_plots() and multi_mag_plot()
```

# Load data

```{r}
gs <- load_gs(here::here("out/GatingSets/RSTR_Th_GatingSet"))

if(!dir.exists(here::here("out/Th_CD4_Tcells_Analysis_of_CD4"))) {
  cat(sprintf("Creating folder %s\n", here::here("out/Th_CD4_Tcells_Analysis_of_CD4")))
  dir.create(here::here("out/Th_CD4_Tcells_Analysis_of_CD4"), recursive = T)
}
```

# Extract frequencies

```{r}
# Add IL17a+ gate directly under CD4+
cd4_il17a_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/IL17a/IL17a+"

gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_il17a_path),
           parent = "CD4+", name = "IL17a+")

# Add other gates
cd4_roryt_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/RORyT+"
cd4_tbet_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/TBET+"
cd4_ifng_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/IFNg+"
cd4_il17a_path_new <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/IL17a+"

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_roryt_path,
                                                         "&!", cd4_tbet_path))))),
           parent = "CD4+", name = "RORyT+TBET-")

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("!", cd4_roryt_path,
                                                         "&", cd4_tbet_path))))),
           parent = "CD4+", name = "RORyT-TBET+")

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("!", cd4_roryt_path,
                                                         "&!", cd4_tbet_path))))),
           parent = "CD4+", name = "RORyT-TBET-")

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_roryt_path,
                                                         "&", cd4_tbet_path))))),
           parent = "CD4+", name = "RORyT+TBET+")

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_ifng_path,
                                                         "&", cd4_il17a_path_new))))),
           parent = "CD4+", name = "IFNg+IL17a+")

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_ifng_path,
                                                         "&!", cd4_il17a_path_new))))),
           parent = "CD4+", name = "IFNg+IL17a-")

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("!", cd4_ifng_path,
                                                         "&", cd4_il17a_path_new))))),
           parent = "CD4+", name = "IFNg-IL17a+")

recompute(gs)

# Get nodes of interest
nodes <- c("/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/CD154+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/CD137+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/OX40+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/CTLA4+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/CD45RA+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/CCR7+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/CXCR3+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/CCR6+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/RORyT+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/TBET+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/IFNg+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/IL17a+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/RORyT+TBET-",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/RORyT-TBET+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/RORyT-TBET-",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/RORyT+TBET+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/IFNg+IL17a+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/IFNg+IL17a-",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4 Positive/CD4+/IFNg-IL17a+")
nodes_short <- str_replace(nodes, "\\/Time\\/Cells\\/CD3\\+\\CD14\\-\\CD19\\-\\/Singlets\\/Live\\/CD3\\+\\ Lymphocytes\\/CD4 Positive\\/CD4\\+\\/", "")

# Get counts
count_list <- list()

for(pop in nodes) {
  current_counts <- pData(gs) %>%
    tibble::rownames_to_column("rowname") %>%
    left_join(gs_pop_get_count_fast(gs, subpopulations = pop), by = c("rowname" = "name")) %>%
    dplyr::rename(Subpop = Count) %>%
    dplyr::select(rowname, "SAMPLE ID", "EXPERIMENT NAME", Stim, Status, Subpop, ParentCount) %>%
    mutate(Freq = (Subpop/ParentCount)*100)
  
  current_counts$Status <- factor(current_counts$Status, levels = c("RSTR", "LTBI"))
  count_list[[pop]] <- current_counts
}

names(count_list) <- nodes_short

# Set color scheme and stims
fill_colors <- c("RSTR" = "#984EA3", "LTBI" = "#4DAF4A")
stims <- c("DMSO", "PP1", "TB WCL")
```

# CD154

```{r, fig.width=4, fig.height=5}
cd154_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[1]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"), 
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[1],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 20))
                                })
names(cd154_plots) <- stims
cd154_plots
```

# CD137

```{r, fig.width=4, fig.height=5}
cd137_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[2]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"), 
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[2],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 10))
                                })
names(cd137_plots) <- stims
cd137_plots
```

# OX40

```{r, fig.width=4, fig.height=5}
ox40_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[3]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[3],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 50))
                                })
names(ox40_plots) <- stims
ox40_plots
```

# CTLA-4

```{r, fig.width=4, fig.height=5}
ctla4_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[4]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[4],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 50))
                                })
names(ctla4_plots) <- stims
ctla4_plots
```

# CD45RA

```{r, fig.width=4, fig.height=5}
cd45ra_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[5]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[5],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(cd45ra_plots) <- stims
cd45ra_plots
```

# CCR7

```{r, fig.width=4, fig.height=5}
ccr7_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[6]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[6],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(50, 100))
                                })
names(ccr7_plots) <- stims
ccr7_plots
```

# CXCR3

```{r, fig.width=4, fig.height=5}
cxcr3_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[7]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[7],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(cxcr3_plots) <- stims
cxcr3_plots
```

# CCR6

```{r, fig.width=4, fig.height=5}
ccr6_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[8]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[8],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 50))
                                })
names(ccr6_plots) <- stims
ccr6_plots
```

# RORyT

```{r, fig.width=4, fig.height=5}
roryt_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[9]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[9],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 10))
                                })
names(roryt_plots) <- stims
roryt_plots
```

# TBET

```{r, fig.width=4, fig.height=5}
tbet_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[10]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[10],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(tbet_plots) <- stims
tbet_plots
```

# IFNg

```{r, fig.width=4, fig.height=5}
ifng_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[11]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[11],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 4))
                                })
names(ifng_plots) <- stims
ifng_plots
```

# IL17a

```{r, fig.width=4, fig.height=5}
il17a_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[12]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[12],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 0.5))
                                })
names(il17a_plots) <- stims
il17a_plots
```

# RORyT+TBET-

```{r, fig.width=4, fig.height=5}
th17_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[13]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[13],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 2))
                                })
names(th17_plots) <- stims
th17_plots
```

# RORyT-TBET+

```{r, fig.width=4, fig.height=5}
rorytn_tbetp_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[14]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[14],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(rorytn_tbetp_plots) <- stims
rorytn_tbetp_plots
```

# RORyT-TBET-

```{r, fig.width=4, fig.height=5}
roryt_tbet_dn_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[15]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[15],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(roryt_tbet_dn_plots) <- stims
roryt_tbet_dn_plots
```

# RORyT+TBET+

```{r, fig.width=4, fig.height=5}
roryt_tbet_dp_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[16]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[16],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 10))
                                })
names(roryt_tbet_dp_plots) <- stims
roryt_tbet_dp_plots
```

# IFNg+IL17a+

```{r, fig.width=4, fig.height=5}
ifng_il17a_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[17]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[17],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 0.15))
                                })
names(ifng_il17a_plots) <- stims
ifng_il17a_plots
```

# IFNg+IL17a-

```{r, fig.width=4, fig.height=5}
ifngp_il17an_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[18]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[18],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 5))
                                })
names(ifngp_il17an_plots) <- stims
ifngp_il17an_plots
```

# IFNg-IL17a+

```{r, fig.width=4, fig.height=5}
ifngn_il17ap_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[19]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[19],
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 0.5))
                                })
names(ifngn_il17ap_plots) <- stims
ifngn_il17ap_plots
```

# Save plots 

```{r}
cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_CD154_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(cd154_plots[["DMSO"]])
print(cd154_plots[["PP1"]])
print(cd154_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_CD137_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(cd137_plots[["DMSO"]])
print(cd137_plots[["PP1"]])
print(cd137_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_OX40_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(ox40_plots[["DMSO"]])
print(ox40_plots[["PP1"]])
print(ox40_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_CTLA4_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(ctla4_plots[["DMSO"]])
print(ctla4_plots[["PP1"]])
print(ctla4_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_CD45RA_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(cd45ra_plots[["DMSO"]])
print(cd45ra_plots[["PP1"]])
print(cd45ra_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_CCR7_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(ccr7_plots[["DMSO"]])
print(ccr7_plots[["PP1"]])
print(ccr7_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_CXCR3_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(cxcr3_plots[["DMSO"]])
print(cxcr3_plots[["PP1"]])
print(cxcr3_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_CCR6_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(ccr6_plots[["DMSO"]])
print(ccr6_plots[["PP1"]])
print(ccr6_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_RORyT_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(roryt_plots[["DMSO"]])
print(roryt_plots[["PP1"]])
print(roryt_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_TBET_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(tbet_plots[["DMSO"]])
print(tbet_plots[["PP1"]])
print(tbet_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_IFNg_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(ifng_plots[["DMSO"]])
print(ifng_plots[["PP1"]])
print(ifng_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_IL17a_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(il17a_plots[["DMSO"]])
print(il17a_plots[["PP1"]])
print(il17a_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_RORyTpos_TBETneg_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(th17_plots[["DMSO"]])
print(th17_plots[["PP1"]])
print(th17_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_RORyTneg_TBETpos_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(rorytn_tbetp_plots[["DMSO"]])
print(rorytn_tbetp_plots[["PP1"]])
print(rorytn_tbetp_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_RORyT_TBET_DN_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(roryt_tbet_dn_plots[["DMSO"]])
print(roryt_tbet_dn_plots[["PP1"]])
print(roryt_tbet_dn_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_RORyT_TBET_DP_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(roryt_tbet_dp_plots[["DMSO"]])
print(roryt_tbet_dp_plots[["PP1"]])
print(roryt_tbet_dp_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_IFNg_IL17a_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(ifng_il17a_plots[["DMSO"]])
print(ifng_il17a_plots[["PP1"]])
print(ifng_il17a_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_IFNgpos_IL17aneg_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(ifngp_il17an_plots[["DMSO"]])
print(ifngp_il17an_plots[["PP1"]])
print(ifngp_il17an_plots[["TB WCL"]])
dev.off()

cairo_pdf(file=here::here("out/Th_CD4_Tcells_Analysis_of_CD4/Th_CD4_IFNgneg_IL17apos_plots_of_CD4.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial") # default unit is inches, default font is Helvetica.
print(ifngn_il17ap_plots[["DMSO"]])
print(ifngn_il17ap_plots[["PP1"]])
print(ifngn_il17ap_plots[["TB WCL"]])
dev.off()
```
