---
title: "Treg Panel CD137+&OX40+ CD4 T cells Analysis"
author: "Jolie Phan"
output: 
  html_document:
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: 4
date: "version `r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---

Of !CD154+&CD137+&OX40&!CTLA4 CD4 T cells, analyze the expression of FoxP3, CD25, CD39, CD73, and IL-10.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Load libraries

```{r}
library(tidyverse)
library(flowWorkspace)
library(here)
library(ggplot2)
library(ggbeeswarm)
library(ggh4x)
source(here::here("scripts/Helper_Functions.R")) # for make_mag_plots() and multi_mag_plot()
```

# Load data

```{r}
gs <- load_gs(here::here("out/GatingSets/RSTR_Treg_GatingSet"))
```

# Add new gates

```{r}
# Grab CD4 gate paths
cd4_cd154_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD154+"
cd4_cd137_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD137+"
cd4_ox40_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/OX40+"
cd4_ctla4_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CTLA4+"
cd4_foxp3_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/FOXP3+"
cd4_cd25_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD25+"
cd4_cd39_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD39+"
cd4_cd73_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD73+"
cd4_il10_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/IL10+"

# Add CD137+ AND OX40+ gate, excluding CD154 and CTLA4
gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("!", cd4_cd154_path,
                                                         "&", cd4_cd137_path,
                                                         "&", cd4_ox40_path,
                                                         "&!", cd4_ctla4_path))))),
           parent = "CD4+", name = "CD4_CD137+_AND_OX40+")

# Add other gates under CD137+_AND_OX40+ gates
gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_foxp3_path,
                                                         "&", cd4_cd25_path))))),
           parent = "CD4_CD137+_AND_OX40+", name = "FOXP3+CD25+")

gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_cd154_path),
           parent = "CD4_CD137+_AND_OX40+", name = "CD154+")

gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_cd137_path),
           parent = "CD4_CD137+_AND_OX40+", name = "CD137+")

gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_ox40_path),
           parent = "CD4_CD137+_AND_OX40+", name = "OX40+")

gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_ctla4_path),
           parent = "CD4_CD137+_AND_OX40+", name = "CTLA4+")

gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_cd25_path),
           parent = "CD4_CD137+_AND_OX40+", name = "CD25+")

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_cd39_path,
                                                         "&", cd4_cd73_path))))),
           parent = "CD4_CD137+_AND_OX40+", name = "CD39+CD73+")

gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_il10_path),
           parent = "CD4_CD137+_AND_OX40+", name = "IL10+")

# Recompute the GatingSet 
flowWorkspace::recompute(gs)
```

# Extract frequencies

First, extract the frequencies of CD137+&OX40+ CD4 T cells.

```{r}
cd137_ox40_node <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+"

cd137_ox40_counts <- pData(gs) %>%
  tibble::rownames_to_column("rowname") %>%
  left_join(gs_pop_get_count_fast(gs, subpopulations = cd137_ox40_node), by = c("rowname" = "name")) %>%
  dplyr::rename(Subpop = Count) %>%
  dplyr::select(rowname, "SAMPLE ID", "EXPERIMENT NAME", Stim, Status, Subpop, ParentCount) %>%
  mutate(Freq = (Subpop/ParentCount)*100)
  
cd137_ox40_counts$Status <- factor(cd137_ox40_counts$Status, levels = c("RSTR", "LTBI"))
```

Next, extract the frequencies of all other markers.

```{r}
nodes <- c("/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+/FOXP3+CD25+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+/CD154+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+/CD137+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+/OX40+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+/CTLA4+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+/CD25+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+/CD39+CD73+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD137+_AND_OX40+/IL10+")
nodes_short <- str_replace(nodes, "\\/Time\\/Cells\\/CD3\\+\\CD14\\-\\CD19\\-\\/Singlets\\/Live\\/CD3\\+\\ Lymphocytes\\/CD4\\+\\/CD4\\_\\CD137\\+\\_AND\\_\\OX40\\+\\/", "")

count_list <- list()

for(pop in nodes) {
  current_counts <- pData(gs) %>%
    tibble::rownames_to_column("rowname") %>%
    left_join(gs_pop_get_count_fast(gs, subpopulations = pop), by = c("rowname" = "name")) %>%
    dplyr::rename(Subpop = Count) %>%
    dplyr::select(rowname, "SAMPLE ID", "EXPERIMENT NAME", Stim, Status, Subpop, ParentCount) %>%
    mutate(Freq = (Subpop/ParentCount)*100)
  
  current_counts$Status <- factor(current_counts$Status, levels = c("RSTR", "LTBI"))
  count_list[[pop]] <- current_counts
}

names(count_list) <- nodes_short

# Set color scheme and stims
fill_colors <- c("RSTR" = "#984EA3", "LTBI" = "#4DAF4A")
stims <- c("DMSO", "PP1", "TB WCL")
status <- c("RSTR", "LTBI")
```

# Boxplots

## CD137+&OX40+

Compare between RSTR vs. LTBI.

```{r, fig.width=4, fig.height=5}
cd137_ox40_plots_status <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(cd137_ox40_counts, current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"), 
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = "CD137+OX40+",
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 1.5))
                                })
names(cd137_ox40_plots_status) <- stims
cd137_ox40_plots_status
```

Compare among stims.

```{r, fig.width=6, fig.height=5}
cd137_ox40_plots_stim <- purrr::pmap(.l = list(status),
                                .f = function(n) {
                                  multi_mag_plot(cd137_ox40_counts, current_status = n,  groups_to_compare = c("DMSO", "PP1", "TB WCL"), 
                                                 subtitle = "CD137+OX40+", fill_colors = fill_colors, y_axis_text = "% CD4 T Cells")
                                })
names(cd137_ox40_plots_stim) <- status
cd137_ox40_plots_stim
```

## FOXP3+&CD25+

```{r, fig.width=4, fig.height=5}
foxp3_cd25_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[1]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[1],
                                                 y_axis_text = "% CD137+&OX40+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 50))
                              })
names(foxp3_cd25_plots) <- stims
foxp3_cd25_plots
```

## CD154

```{r, fig.width=4, fig.height=5}
cd154_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[2]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[2],
                                                 y_axis_text = "% CD137+&OX40+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(cd154_plots) <- stims
cd154_plots
```

## CD137

```{r, fig.width=4, fig.height=5}
cd137_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[3]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[3],
                                                 y_axis_text = "% CD137+&OX40+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(cd137_plots) <- stims
cd137_plots
```

## OX40

```{r, fig.width=4, fig.height=5}
ox40_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[4]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[4],
                                                 y_axis_text = "% CD137+&OX40+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(ox40_plots) <- stims
ox40_plots
```

## CTLA-4

```{r, fig.width=4, fig.height=5}
ctla4_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[5]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[5],
                                                 y_axis_text = "% CD137+&OX40+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(ctla4_plots) <- stims
ctla4_plots
```

## CD25

```{r, fig.width=4, fig.height=5}
cd25_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[6]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[6],
                                                 y_axis_text = "% CD137+&OX40+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100))
                                })
names(cd25_plots) <- stims
cd25_plots
```

## CD39+&CD73+

```{r, fig.width=4, fig.height=5}
cd39_cd73_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[7]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[7],
                                                 y_axis_text = "% CD137+&OX40+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 5))
                                })
names(cd39_cd73_plots) <- stims
cd39_cd73_plots
```

## IL10

```{r, fig.width=4, fig.height=5}
il10_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[8]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("RSTR", "LTBI"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Status", subtitle = nodes_short[8],
                                                 y_axis_text = "% CD137+&OX40+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 5))
                                })
names(il10_plots) <- stims
il10_plots
```
