---
title: "Treg Panel CD4 T cells Analysis"
author: "Jolie Phan"
output: 
  html_document:
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: 4
date: "version `r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---

Of CD154+ and/or CD137+ CD4 T cells, analyze the expression of OX40, CTLA-4, FoxP3, CD25, CD39, CD73, IL-10, and CCR7.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Load libraries

```{r}
library(tidyverse)
library(flowWorkspace)
library(here)
library(ggplot2)
library(ggbeeswarm)
library(ggh4x)
library(ggpubr)
source(here::here("scripts/Helper_Functions.R")) # for make_mag_plots() and multi_mag_plot()
```

# Load data

```{r}
gs <- load_gs(here::here("out/GatingSets/RSTR_Treg_GatingSet"))

# Add shortened experiment name
pData(gs)$`EXPERIMENT NAME`  <- str_replace_all(pData(gs)$`EXPERIMENT NAME`,
                                                "20220415 RSTR INS Treg B1",
                                                "B1")

pData(gs)$`EXPERIMENT NAME`  <- str_replace_all(pData(gs)$`EXPERIMENT NAME`,
                                                "20220429 RSTR INS Treg B2",
                                                "B2")

pData(gs)$Batch <- factor(pData(gs)$`EXPERIMENT NAME`, levels = c("B1", "B2"))
```

# Add new gates

```{r}
# Grab CD4 gate paths
cd4_cd154_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD154+"
cd4_cd137_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD137+"
cd4_ox40_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/OX40+"
cd4_ctla4_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CTLA4+"
cd4_foxp3_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/FOXP3+"
cd4_cd25_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD25+"
cd4_cd39_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD39+"
cd4_cd73_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD73+"
cd4_ccr7_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CCR7+"
cd4_il10_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/IL10+"

# Add CD154+ OR CD137+ gate
gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_cd154_path,
                                                         "&", cd4_cd137_path))))),
           parent = "CD4+", name = "CD4_CD154+_OR_CD137+")

# Add other gates under CD154+_OR_CD137+ gates
gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_ox40_path),
           parent = "CD4_CD154+_OR_CD137+", name = "OX40+")
gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_ctla4_path),
           parent = "CD4_CD154+_OR_CD137+", name = "CTLA4+")
gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_foxp3_path,
                                                         "&", cd4_cd25_path))))),
           parent = "CD4_CD154+_OR_CD137+", name = "FOXP3+CD25+")

gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_foxp3_path,
                                                         "&!", cd4_cd25_path))))),
           parent = "CD4_CD154+_OR_CD137+", name = "FOXP3+CD25-")
gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_foxp3_path),
           parent = "CD4_CD154+_OR_CD137+", name = "FOXP3+")
gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_cd25_path),
           parent = "CD4_CD154+_OR_CD137+", name = "CD25+")
gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_cd39_path,
                                                         "&", cd4_cd73_path))))),
           parent = "CD4_CD154+_OR_CD137+", name = "CD39+CD73+")
gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_cd39_path),
           parent = "CD4_CD154+_OR_CD137+", name = "CD39+")
gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_cd73_path),
           parent = "CD4_CD154+_OR_CD137+", name = "CD73+")
gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_ccr7_path),
           parent = "CD4_CD154+_OR_CD137+", name = "CCR7+")
gs_pop_add(gs, lapply(gs, gh_pop_get_gate, y = cd4_il10_path),
           parent = "CD4_CD154+_OR_CD137+", name = "IL10+")

# Recompute the GatingSet 
flowWorkspace::recompute(gs)
```

# Extract frequencies

First, extract the frequencies of CD154+|CD137+ CD4 T cells.

```{r}
cd154_cd137_node <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+"

cd154_cd137_counts <- pData(gs) %>%
  tibble::rownames_to_column("rowname") %>%
  left_join(gs_pop_get_count_fast(gs, subpopulations = cd154_cd137_node), by = c("rowname" = "name")) %>%
  dplyr::rename(Subpop = Count) %>%
  dplyr::select(rowname, "SAMPLE ID", "Batch", Stim, Status, Subpop, ParentCount) %>%
  mutate(Freq = (Subpop/ParentCount)*100)
  
cd154_cd137_counts$Status <- factor(cd154_cd137_counts$Status, levels = c("RSTR", "LTBI"))
```

Extract the frequencies of CD137+ CD4 T cells.

```{r}
cd137_counts <- pData(gs) %>%
  tibble::rownames_to_column("rowname") %>%
  left_join(gs_pop_get_count_fast(gs, subpopulations = cd4_cd137_path), by = c("rowname" = "name")) %>%
  dplyr::rename(Subpop = Count) %>%
  dplyr::select(rowname, "SAMPLE ID", "Batch", Stim, Status, Subpop, ParentCount) %>%
  mutate(Freq = (Subpop/ParentCount)*100)
  
cd137_counts$Status <- factor(cd137_counts$Status, levels = c("RSTR", "LTBI"))
```

Next, extract the frequencies of all other markers.
```{r}
nodes <- c("/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/OX40+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/CTLA4+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/FOXP3+CD25+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/FOXP3+CD25-",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/CD25+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/IL10+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/CD39+CD73+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/CD39+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/CD73+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/CCR7+",
           "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+/FOXP3+")
nodes_short <- str_replace(nodes, "\\/Time\\/Cells\\/CD3\\+\\CD14\\-\\CD19\\-\\/Singlets\\/Live\\/CD3\\+\\ Lymphocytes\\/CD4\\+\\/CD4\\_\\CD154\\+\\_\\OR\\_\\CD137\\+\\/", "")

count_list <- list()

for(pop in nodes) {
  current_counts <- pData(gs) %>%
    tibble::rownames_to_column("rowname") %>%
    left_join(gs_pop_get_count_fast(gs, subpopulations = pop), by = c("rowname" = "name")) %>%
    dplyr::rename(Subpop = Count) %>%
    dplyr::select(rowname, "SAMPLE ID", "Batch", Stim, Status, Subpop, ParentCount) %>%
    mutate(Freq = (Subpop/ParentCount)*100)
  
  current_counts$Status <- factor(current_counts$Status, levels = c("RSTR", "LTBI"))
  count_list[[pop]] <- current_counts
}

names(count_list) <- nodes_short

# Add column indicating "Node" in FOXP3 and CD25 count dataframes
foxp3_cd25_counts <- count_list[[nodes_short[3]]]
foxp3_cd25_counts["Node"] <- nodes_short[3]

foxp3_counts <- count_list[[nodes_short[4]]] 
foxp3_counts["Node"] <- nodes_short[4]

cd25_counts <- count_list[[nodes_short[5]]] 
cd25_counts["Node"] <- nodes_short[5]

# Combine FOXP3 and CD25 count dataframes 
treg_counts <- bind_rows(foxp3_cd25_counts, foxp3_counts) %>%
  bind_rows(cd25_counts)

nodes_compare <- c(nodes_short[3], nodes_short[4], nodes_short[5])

# Set color scheme and stims
fill_colors <- c("B1" = "#F8766D", "B2" = "#00BFC4")
stims <- c("DMSO", "PP1", "TB WCL")
```

# CD154|CD137

```{r, fig.width=4, fig.height=5}
cd154_cd137_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(cd154_cd137_counts, current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"), 
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = "CD154+|CD137+",
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 6), facet_by = "Status")
                                })
names(cd154_cd137_plots) <- stims
cd154_cd137_plots
```

# CD137

```{r, fig.width=4, fig.height=5}
cd137_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(cd137_counts, current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"), 
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = "CD137+",
                                                 y_axis_text = "% CD4 T Cells", y_axis_size = 15,   ylim = c(0, 10), facet_by = "Status")
                                })
names(cd137_plots) <- stims
cd137_plots
```

# OX40

```{r, fig.width=4, fig.height=5}
# There are two outliers in the PP1-stimmed samples, so the PP1 data will be plotted separately w/o the outlier samples
ox40_plots <- purrr::pmap(.l = list(stims[-2]),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[1]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[1],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(75, 100), facet_by = "Status")
                                })
names(ox40_plots) <- stims[-2]

ox40_counts_no_outlier <- count_list[[nodes_short[1]]] %>%
  dplyr::filter(Stim == "PP1") %>%
  dplyr::filter(`SAMPLE ID` != "RS102248" & `SAMPLE ID` != "RS102111")

ox40_pp1_plot <- make_mag_plots(count_list[[nodes_short[1]]], counts_no_outlier = ox40_counts_no_outlier, current_stim = "PP1", num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[1],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(75, 100), facet_by = "Status")

ox40_plots
ox40_pp1_plot
```

# CTLA-4

```{r, fig.width=4, fig.height=5}
ctla4_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[2]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[2],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 100), facet_by = "Status")
                                })
names(ctla4_plots) <- stims
ctla4_plots
```

# FOXP3 and CD25

```{r, fig.width=4, fig.height=5}
foxp3_cd25_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[3]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[3],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 50), facet_by = "Status")
                              })
names(foxp3_cd25_plots) <- stims
foxp3_cd25_plots

foxp3_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[4]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[4],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 4), facet_by = "Status")
                                })
names(foxp3_plots) <- stims
foxp3_plots

cd25_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[5]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[5],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(40, 100), facet_by = "Status")
                                })
names(cd25_plots) <- stims
cd25_plots
```

# IL10

```{r, fig.width=4, fig.height=5}
il10_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[6]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[6],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 3), facet_by = "Status")
                                })
names(il10_plots) <- stims
il10_plots
```

# CD39 and CD73

```{r, fig.width=4, fig.height=5}
cd39_cd73_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[7]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[7],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 4.5), facet_by = "Status")
                                })
names(cd39_cd73_plots) <- stims
cd39_cd73_plots

cd39_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[8]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[8],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 30), facet_by = "Status")
                                })
names(cd39_plots) <- stims
cd39_plots

cd73_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[9]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[9],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 50), facet_by = "Status")
                                })
names(cd73_plots) <- stims
cd73_plots
```

# CCR7

```{r, fig.width=4, fig.height=5}
ccr7_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[10]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[10],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(60, 100), facet_by = "Status")
                                })
names(ccr7_plots) <- stims
ccr7_plots
```

# FoxP3

```{r, fig.width=4, fig.height=5}
foxp3_plots <- purrr::pmap(.l = list(stims),
                                .f = function(n) {
                                  make_mag_plots(count_list[[nodes_short[11]]], current_stim = n, num_comparisons = length(stims), groups_to_compare = c("B1", "B2"),
                                                 paired = FALSE, adjust_p = FALSE, fill_colors = fill_colors, group_by_colname = "Batch", subtitle = nodes_short[11],
                                                 y_axis_text = "% CD154+|CD137+ CD4 T Cells", y_axis_size = 15,   ylim = c(0, 50), facet_by = "Status")
                                })
names(foxp3_plots) <- stims
foxp3_plots
```
