---
title: "RSTR Dim Red on Treg CD4 T cells"
author: "Jolie Phan"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: 4
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Run UMAP on CD154+|CD137+ CD4+ events. 

# Load libraries

```{r, message=FALSE}
library(openCyto)
library(CytoML) 
library(flowCore) 
library(flowWorkspace) 
library(here)
library(tidyverse)
library(uwot)
library(ggplot2)
library(scales)
library(cowplot)
library(hues)
library(ggrepel)
library(ggpubr)
library(ggrastr)
source(here::here("scripts/Helper_Functions.R"))
```

# Load data

```{r}
date <- 20221004
save_output <- TRUE
rerun_dimred <- FALSE

gs <- load_gs(here::here("out/GatingSets/RSTR_Treg_GatingSet"))

if(!dir.exists(here::here("out/UMAP"))) {
  cat(sprintf("Creating folder %s\n", here::here("out/UMAP")))
  dir.create(here::here("out/UMAP"), recursive = T)
}
```

# Add gates

```{r}
# Grab CD4 gate paths
cd4_cd154_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD154+"
cd4_cd137_path <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD137+"

# Add CD154+ OR CD137+ gate
gs_pop_add(gs, eval(substitute(flowWorkspace::booleanFilter(v),
                               list(v = as.symbol(paste0("", cd4_cd154_path,
                                                         "|", cd4_cd137_path))))),
           parent = "CD4+", name = "CD4_CD154+_OR_CD137+")

recompute(gs)
```

# Extract mfi data

```{r}
cd4_gates_for_dimred <- c(
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD154+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD137+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/OX40+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CTLA4+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/FOXP3+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD25+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD39+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD73+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CCR7+",
  "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/IL10+"
  )
```

```{r}
# Get counts for CD154+|CD137+ CD4 T cells
cd4_cd154_cd137_parentGate <- "/Time/Cells/CD3+CD14-CD19-/Singlets/Live/CD3+ Lymphocytes/CD4+/CD4_CD154+_OR_CD137+"

pop_counts <- pData(gs) %>%
  tibble::rownames_to_column("rowname") %>%
  left_join(gs_pop_get_count_fast(gs, subpopulations = cd4_cd154_cd137_parentGate), by = c("rowname" = "name")) %>%
  dplyr::rename(CD4_CD154_CD137 = Count) %>%
  dplyr::select(rowname, "SAMPLE ID", "EXPERIMENT NAME", Stim, Status, CD4_CD154_CD137) %>%
  dplyr::filter(Stim == "PP1")
```

```{r}
# Extract data for dimensionality reduction (not actually sampling)
call_sampleGatingHierarchy_for_cd4 <- function(currentSampleName) {
  sampleGatingHierarchy(gs[[currentSampleName]], cd4_cd154_cd137_parentGate, n = NULL, otherGates = cd4_gates_for_dimred)
}

cd4_cd154_cd137_data <- map_dfr(pop_counts$rowname, call_sampleGatingHierarchy_for_cd4) 
dim(cd4_cd154_cd137_data)
knitr::kable(head(cd4_cd154_cd137_data))
```

# Perform Dimensionality Reduction

```{r}
cols_4_dimred <- c("CD3", "CD8a", "CD4", "CD154", "CD137", "CTLA4", "OX40", "FOXP3", "CD25", "CD39", "CD73", "CCR7", "IL10")
# Scale CD4 COMPASS subset counts 
cd4.scaled_dimred_input <- cd4_cd154_cd137_data %>%
  dplyr::select("EXPERIMENT NAME", all_of(cols_4_dimred)) %>%
  group_by(`EXPERIMENT NAME`) %>%
  nest() %>%
  ungroup() %>%
  mutate(data = lapply(data, function(df) {as.data.frame(scale(as.matrix(df)))})) %>%
  unnest(cols = c(data)) %>%
  rename_at(vars(all_of(cols_4_dimred)),function(x) paste0(x,".scaled")) %>% 
  dplyr::select(-"EXPERIMENT NAME")

cd4_cd154_cd137_data <- cbind(cd4_cd154_cd137_data, cd4.scaled_dimred_input)
```

```{r}
if(rerun_dimred) {
  print("Running UMAP")
  set.seed(date)
  print(Sys.time())
  cd4_cd154_cd137_dimred_out <- cd4_cd154_cd137_data %>%
    # Run CD3, co-receptor, cytokine, memory, and activation markers through UMAP
    dplyr::select(all_of(paste0(cols_4_dimred, ".scaled"))) %>%
    uwot::umap(spread = 9, min_dist = 0.02, n_threads = 7)
  print(Sys.time())
  cd4_cd154_cd137_w_umap <- cbind(as.data.frame(cd4_cd154_cd137_dimred_out) %>%
    dplyr::rename(x.umap = V1, y.umap = V2),
  cd4_cd154_cd137_data)
  if(save_output) {
    saveRDS(cd4_cd154_cd137_w_umap, here::here(sprintf("out/UMAP/%s_Treg_CD4_CD154_CD137_UMAP_Unsampled.rds", date)))
    }
} else {
  # Assuming UMAP results are already saved
  print("Loading saved UMAP run")
  cd4_cd154_cd137_w_umap <- readRDS(here::here(sprintf("out/UMAP/%s_Treg_CD4_CD154_CD137_UMAP_Unsampled.rds", date)))
}
```

# Plot UMAP results

```{r}
set.seed(date)
cd4_cd154_cd137_w_umap <- cd4_cd154_cd137_w_umap[sample(nrow(cd4_cd154_cd137_w_umap), nrow(cd4_cd154_cd137_w_umap)),]
```

```{r}
# Arial font setup. Downloaded afms from https://github.com/microsoft/microsoft-r-open/tree/ec3fd89e5fb5794bd8149905c134ad801bb61800
Arial <- Type1Font(family = "Arial",
                   metrics = c(here::here("data/Arial_afm/ArialMT.afm"),
                               here::here("data/Arial_afm/ArialMT-Bold.afm"), 
                              here::here("data/Arial_afm/ArialMT-Italic.afm"),                         
                              here::here("data/Arial_afm/ArialMT-BoldItalic.afm")))
windowsFonts("Arial" = windowsFont("Arial"))
pdfFonts(Arial = Arial)

boolColorScheme <- c("FALSE" = "#9E9E9E", "TRUE" = "#C7254A")

cd4_cd154_cd137_w_umap <- cd4_cd154_cd137_w_umap %>%
  mutate(dof = rowSums(dplyr::select(., all_of(cd4_gates_for_dimred[-c(1, 2)]))))

stim_labs <- "PP1"
names(stim_labs) <- "PP1"
group_labs <- c("RSTR", "LTBI")
names(group_labs) <- c("RSTR", "LTBI")

base_dimred_plot <- function(currentColumn, pointSize = 0.02, colorScheme = NA) {
  p <- ggplot(cd4_cd154_cd137_w_umap, aes(x=x.umap, y=y.umap,
                                       colour=if(currentColumn %in% c("EXPERIMENT NAME", "SAMPLE ID")) {
                                         factor(!!as.name(currentColumn))
                                         } else {
                                           as.logical(!!as.name(currentColumn))
                                           })) +
    geom_point_rast(shape=20, alpha=0.8, size=pointSize) +
    facet_grid(Status ~ Stim, switch="y",
               labeller = labeller(Status = group_labs, Stim = stim_labs)) +
    theme_bw() +
    theme(plot.title=element_text(hjust = 0.5, size=22, face="bold"),
          axis.text=element_blank(),
          axis.line=element_blank(),
          axis.ticks=element_blank(),
          axis.title=element_blank(),
          strip.text=element_text(face="bold", size=10),
          panel.grid.major = element_blank(),
          legend.title=element_text(face="bold", size=14),
          strip.text.x = element_text(margin = margin(0.15,0,0.15,0, "cm")))
  if(!anyNA(colorScheme)) {
    p <- p + scale_color_manual(values = colorScheme)
  }
  if(currentColumn %in% c("EXPERIMENT NAME", "SAMPLE ID")) {
    p <- p + labs(color = currentColumn) +
      guides(colour = guide_legend(override.aes = list(size=7))) +
      theme(legend.title = element_text(size=10),
            legend.text = element_text(size=10),
            legend.position = "bottom") +
      scale_colour_manual(values=as.character(iwanthue(length(unique(cd4_cd154_cd137_w_umap[,currentColumn])))))
  } else {
    p <- p + theme(legend.position = "none")
  }
  p
}
```

## Look for Batch and Patient sub-clustering

```{r, fig.width=4, fig.height=5}
base_dimred_plot("EXPERIMENT NAME")

cairo_pdf(file=here::here("out/UMAP/Treg_UMAP_by_Batch.pdf"), width=4, height=5,
          onefile = TRUE, bg = "transparent", family = "Arial")
base_dimred_plot("EXPERIMENT NAME")
dev.off()
```

```{r, fig.width=7, fig.height=8}
base_dimred_plot("SAMPLE ID")

cairo_pdf(file=here::here("out/UMAP/Treg_UMAP_by_PTID.pdf"), width=7, height=8,
          onefile = TRUE, bg = "transparent", family = "Arial")
base_dimred_plot("SAMPLE ID")
dev.off()
```

## Individual marker expression localization

```{r, fig.width=6, fig.height=6}
for(cg in cd4_gates_for_dimred) {
  print(base_dimred_plot(cg, colorScheme = boolColorScheme) +
          labs(title = sprintf("CD154+|CD137+ CD4 T cells UMAP\nColored by %s", sub(".*\\/([^(\\/)]+)", "\\1", cg))))
}

cairo_pdf(file=here::here("out/UMAP/Treg_UMAP_by_Single_Markers.pdf"), width=6, height=6,
          onefile = TRUE, bg = "transparent", family = "Arial")
for(cg in cd4_gates_for_dimred) {
  print(base_dimred_plot(cg, colorScheme = boolColorScheme) +
          labs(title = sprintf("CD154+|CD137+ CD4 T cells UMAP\nColored by %s", sub(".*\\/([^(\\/)]+)", "\\1", cg))))
}
dev.off()
```